// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:4a132a13-4200-40e1-8ef7-a3ef8edff761",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_wU3eurONt",
    "aws_user_pools_web_client_id": "q49eecvfbj7b1tk83rajvgaer"
};


export default awsmobile;
